# SConstruct for src/fass
#
# Request.cc
#
#      Author: Sara Vallero 
#      Author: Valentina Zaccolo
#

import os
Import('env')

lib_name='fass_rpcm'

# Sources to generate the library
source_files=[
    'Request.cc',
    'RequestSystem.cc',
    'RequestOneProxy.cc',
    'RPCManager.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_core',
    'fass_rpcm',
    'fass_log',
    'fass_client'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))
