# SConstruct for src/rpcm

import os
Import('env')

lib_name='fass_rpcm'

# Sources to generate the library
source_files=[
    'Request.cc',
    'RequestSystem.cc',
    'RequestOneProxy.cc',
    'RequestQueue.cc',
    'RPCManager.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_core',
    'fass_rpcm',
    'fass_log',
    'fass_client',
    'fass_pm',
    'xml2'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))

env.Program('test_queue.cc');
