# SConstruct for src/fass

# ------------------------------------ # 
# HEADER                               #
#                                      #
# Mailto: svallero AT to.infn.it       #
#                                      #
# ------------------------------------ #

import os
Import('env')

lib_name='fass_log'

# Sources to generate the library
source_files=[
    'Log.cc',
    'FassLog.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_log'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))

