# SConstruct for src/fass

import os
Import('env')

lib_name='fass_core'

# Sources to generate the library
source_files=[
    'Fass.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_core',
    'fass_pm',
    'fass_log',
    'fass_config', 
    'fass_rpcm',
    'fass_db',
    'fass_xml',
    'fass_client'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))

env.Program('fassd.cc')

