# SConstruct for src/xml

import os
Import('env')

lib_name='fass_xml'

# Sources to generate the library
source_files=[
    'ObjectXML.cc',
    'VMPool.cc',
    'VMObject.cc',
    'AcctPool.cc',
    'AcctObject.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_log',
    'fass_client',
    'fass_xml'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))
