# SConstruct for src/config

import os
Import('env')

lib_name='fass_config'

# Sources to generate the library
source_files=[
    'Configurator.cc',
    'FassConfigurator.cc',
    'SharesConfigurator.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_log',
    'fass_config'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))

