# SConstruct for src/pm

import os
Import('env')

lib_name='fass_terminator'

# Sources to generate the library
source_files=[
    'Terminator.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_log',
    'fass_client',
    'fass_xml',
    'fass_terminator'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))
