# SConstruct for src/pm

import os
Import('env')

lib_name='fass_pm'

# Sources to generate the library
source_files=[
    'PriorityManager.cc',
    'VMPool.cc',
    'VirtualMachine.cc',
    'InitialShares.cc',
    'BasicPlugin.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_core',
    'fass_rpcm',
    'fass_log',
    'fass_client',
    'fass_pm'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))
