# SConstruct for src/fass

import os
Import('env')

lib_name='fass_client'

# Sources to generate the library
source_files=[
    'XMLRPCClient.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)

# Build daemon
env.Prepend(LIBS=[
    'fass_core',
    'fass_rpcm',
    'fass_log',
    'fass_client'
])

if not env.GetOption('clean'):
    env.ParseConfig(("LDFLAGS='%s'") % (os.environ['LDFLAGS'],))
